### PR TITLE
Improve PKG-INFO for pypi description

### PR DESCRIPTION
**Pull request by fbouliane**
This will add the README, the license and the url in the PKGINFO,
this way, Pypi will be able to get the description of our project.

### CODE REVIEW

**Comment by JoProvost** [comment]
:+1:

**Comment by godp1301** [comment]
👍

**Comment by mat128** [comment]
Markdown isnt supported for description, only RST is :(

**Comment by mat128** [comment]
FOr example: https://pypi.python.org/pypi/netman

**Comment by fbouliane** [comment]
still better than [False](https://pypi.python.org/pypi/fake-switches) ?

**Comment by fbouliane** [comment]
[They](https://github.com/pypa/pypi-legacy/issues/148) suggests to convert from markdown to rst for pypi, toughts ?

**Pull request merged**
